version: '3'

services:
  database:
    image: mariadb:11
    ports:
      - 3306:3306
    restart: always
    volumes:
      - database:/app/data
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}

volumes:
  database:
