version: '3'

services:
  database:
    image: mariadb:11
    ports:
      - 3306:3306
    restart: always
    volumes:
      - database:/app/data
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  arkalis:
    build: arkalis
    ports:
      - 3002:8000
    restart: always
    environment:
      - ARKALIS_JWT_SECRET=${ARKALIS_JWT_SECRET}
      - ARKALIS_ADMIN_MASTER_KEY=${ARKALIS_ADMIN_MASTER_KEY}
      - ARKALIS_DATABASE_URL=mysql://root:${DATABASE_PASSWORD}@database/arkalis
    depends_on:
      database:
        condition: service_healthy

  aoba:
    build: aoba
    ports:
      - 3003:8001
    restart: always
    environment:
      - AOBA_ARKALIS_URL=${AOBA_ARKALIS_URL}
    volumes:
      - ./uploads:/app/uploads

volumes:
  database:
